baseURL = "https://cndoit18.cn/"
defaultContentLanguage = "zh"
languageCode = 'zh-CN'
copyright = '本站遵循 <a href="https://creativecommons.org/licenses/by-nc/4.0/" >CC-BY-NC 4.0</a> 协议.'
title = '小翰的世界'
theme = 'diary'

[params]
favicon = 'images/favicon.svg'
enableReadingTime = true
enableGiscus = true
subtitle = "cndoit18's Blog"

[params.giscus]
data-repo="cndoit18/10x-engineer"
data-repo-id="R_kgDOLlV-zA"
data-category="Announcements"
data-category-id="DIC_kwDOLlV-zM4Cm-CR"
data-mapping="pathname"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-input-position="bottom"
data-theme="preferred_color_scheme"
data-lang="zh-CN"
crossorigin="anonymous"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/tags"
name = "标签"
weight = 1

[[menu.main]]
url = "/categories"
name = "系列"
weight = 2

[[menu.main]]
url = "/about"
name = "关于"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4
