baseURL = "https://cndoit18.cn/"
defaultContentLanguage = "zh"
languageCode = 'zh-CN'
copyright = '本站遵循 <a href="https://creativecommons.org/licenses/by-nc/4.0/" >CC-BY-NC 4.0</a> 协议.'
title = '小翰的世界'
theme = 'diary'

[params]
favicon = 'images/favicon.svg'
enableReadingTime = true
enableGiscus = true
subtitle = "cndoit18's Blog"

[params.giscus]
data_repo = "cndoit18/10x-engineer"
data_repo_id = "R_kgDOLlV-zA"
data_category = "Announcements"
data_category_id = "DIC_kwDOLlV-zM4Cm-CR"
data_mapping = "pathname"
data_strict = "0"
data_reactions_enabled = "1"
data_emit_metadata = "0"
data_input_position = "bottom"
data_theme = "preferred_color_scheme"
data_lang = "zh-CN"
crossorigin = "anonymous"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/tags"
name = "标签"
weight = 1

[[menu.main]]
url = "/categories"
name = "系列"
weight = 2

[[menu.main]]
url = "/about"
name = "关于"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4
